
[urgency_low]
    background = "#6582A380"
    foreground = "#CCE4FFE6"
    frame_color = "#6582A303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A4B6B80"
    foreground = "#CCDEFFE6"
    frame_color = "#3A4B6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
