#Hyprspace
exec-once = hyprctl plugin load '/home/zaryu/Clone/UsedNow/Hyprspace/Hyprspace.so'
bind = $mainMod+Alt, TAB, overview:toggle
plugin {
    overview {
      #Colors
      panelColor = rgba(282a3677)
      workspaceActiveBorder = rgb(ff79c6)
      workspaceInactiveBorder = rgb(44475a)
      dragAlpha = 0
      #Layout
      panelHeight = 200
      panelBorderWidth = 10
      onBottom = 1
      workspaceMargin = 10
      workspaceBorderSize = 1
      overrideAnimSpeed = 2
      exitOnSwitch = true
      showNewWorkspace = false
      showEmptyWorkspace = false
      hideBackgroundLayers = true
      hideOverlayLayers = true
      autoScroll = true
      drawActiveWorkspace = true
      #Gaps
      gapsIn = 10
      gapsOut = 10
      }
  }
