
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

###### SOURCES ######

## Pyprland
source = ~/.config/hypr/UserPrefs/pypr-bind.conf
## hyprspace
source = ~/.config/hypr/UserPrefs/hyprspace.conf
## NWG DOCK hyprland
source = ~/.config/hypr/UserPrefs/nwg-dock.conf
# PLUGINS
source = ~/.config/hypr/plugins/plugins.conf

## StartUP ##
exec-once = xhost si:localuser:root
#exec-once = $scrPath/custom/RainbowBorders.sh &



## Auto-Launch App
#exec-once = sleep 20 && kitty btop


## Custom Bind ##
bind = $mainMod+Shift, K, exec, $scrPath/custom/QuickEdit.sh
bind = $mainMod+Shift, S, exec, Hyde show search
bind = $mainMod+Alt, W, exec, iwmenu -m rofi
bind = $mainMod, W, centerwindow
bind = $mainMod, tab, workspace, m+1 #switchtab
bind = Ctrl, slash, workspace, m+1 #switchtab


# APP'S
bind = $mainMod, B, exec, flatpak run com.brave.Browser #Brave Browser
bind = $mainMod, Return, exec, $term
bind = $mainMod+Alt, E, exec, nautilus
bind = $mainMod+Shift, G, exec, github-desktop


# End4-AGS with HyprPanel
exec-once = agsv1 -b end4 -c ~/.config/ags2/config.js
bind = $mainMod, Space, exec, agsv1 -b end4 -t sideleft
bind = $mainMod+Alt, Space, exec, agsv1 -b end4 -t sideright
#bind = $mainMod+Shift, B, exec, agsv1 run-js 'cycleMode()' -b end4 #toggle bar



#HyprPanel
#exec-once = agsv1 &
#exec-once = agsv1 -r "useTheme('${HOME}/.cache/hyde/landing/wallbash-hyprpanel.json')"
#bind = $Ctrl+Alt, B, exec, agsv1 -t bar-0
#bind = $Ctrl+Alt, N, exec, agsv1 -t notificationsmenu
#bind = $Ctrl+Alt, Space, exec, agsv1 -t dashboardmenu




## Pyprland 
  ##exec-once = /home/zaryu/.nix-profile/bin/pypr
#bind = $mainMod SHIFT, Z, exec, pypr zoom
#bind = $mainMod ALT, P,exec, pypr toggle_dpms
#bind = $mainMod SHIFT, O, exec, pypr shift_monitors +1
#bind = $mainMod, B, exec, pypr expose
#bind = $mainMod, K, exec, pypr change_workspace +1
#bind = $mainMod, J, exec, pypr change_workspace -1
#bind = $mainMod,L,exec, pypr toggle_dpms
#bind = $mainMod SHIFT,M,exec,pypr toggle stb stb-logs
  ## bind = $mainMod+Alt,A,exec,pypr toggle term
#bind = $mainMod,V,exec,pypr toggle volume




