[borders-plus-plus]
enabled = false
failed = false
filename = 'borders-plus-plus.so'

[csgo-vulkan-fix]
enabled = false
failed = false
filename = 'csgo-vulkan-fix.so'

[hyprbars]
enabled = false
failed = false
filename = 'hyprbars.so'

[hyprexpo]
enabled = true
failed = false
filename = 'hyprexpo.so'

[hyprtrails]
enabled = false
failed = false
filename = 'hyprtrails.so'

[hyprwinwrap]
enabled = false
failed = false
filename = 'hyprwinwrap.so'

[repository]
hash = '344a69db96fa8c6dc3b8f1f8f5a75f6eb441cbf2'
name = 'hyprland-plugins'
rev = ''
url = 'https://github.com/hyprwm/hyprland-plugins'